language: r
cache: packages
sudo: required
warnings_are_errors: false
apt_packages:
- libxml2
r_packages:
- XML
- RCurl
- httr
- plyr
- testthat
- covr
after_success:
- Rscript -e 'library(covr);codecov()'
notifications:
  email:
    on_success: change
    on_failure: change
before_install:
- openssl aes-256-cbc -K $encrypted_7719d0814fcd_key -iv $encrypted_7719d0814fcd_iv
  -in tokens.tar.enc -out tokens.tar -d
- tar xvf tokens.tar
