language: r

sudo: required
warnings_are_errors: false
apt_packages:
 - libxml2
 
env:
  global:
    - CRAN: http://cran.rstudio.com

r_packages:
 - XML
 - RCurl
 - httr
 - plyr
 - testthat
 - covr

after_success:
 - Rscript -e 'library(covr);codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
