language: r
cache: packages
sudo: required
warnings_are_errors: false
apt_packages:
- libxml2
r_packages:
- XML
- RCurl
- httr
- plyr
- testthat
- covr
after_success:
- Rscript -e 'library(covr);codecov()'
notifications:
  email:
    on_success: change
    on_failure: change
before_install:
- openssl aes-256-cbc -K $encrypted_0646e44e9c21_key -iv $encrypted_0646e44e9c21_iv -in tokens.tar.enc -out tests/testthat/tokens.tar -d
- tar xvf tests/testthat/tokens.tar
