language: r

sudo: required

apt_packages:
 - libxml2
 
r_binary_packages:
 - XML
 - RCurl
 - httr
 - testthat 
 - covr

after_success:
 - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
